# frozen_string_literal: true

module SolidLog
  module Core
    # Generates ActiveRecord migrations for field promotions
    # When a field is promoted, this creates a timestamped migration file that:
    # 1. Adds a new column to solid_log_entries
    # 2. Creates an index on the new column
    # 3. Backfills existing data from the extra_fields JSON
    class MigrationGenerator
    class << self
      # Generate a migration file for promoting a field
      # @param field [Field] The field to promote
      # @return [String, nil] Path to generated migration file, or nil if error
      def generate_promotion_migration(field)
        return nil unless field.is_a?(Field)

        timestamp = Time.current.utc.strftime("%Y%m%d%H%M%S")
        class_name = "AddPromoted#{field.name.camelize}ToEntries"
        filename = "#{timestamp}_#{class_name.underscore}.rb"

        # Determine where to write the migration
        migration_path = determine_migration_path
        FileUtils.mkdir_p(migration_path) unless Dir.exist?(migration_path)

        file_path = File.join(migration_path, filename)

        # Generate migration content
        content = generate_migration_content(field, class_name)

        # Write file
        File.write(file_path, content)

        SolidLog.logger&.info("Generated promotion migration: #{file_path}")
        file_path
      rescue => e
        SolidLog.logger&.error("Failed to generate migration for field #{field.name}: #{e.message}")
        nil
      end

      private

      # Determine where to write the migration file
      # Tries multiple locations in order of preference
      def determine_migration_path
        candidates = []

        # Rails app log_migrate directory
        candidates << Rails.root.join("db", "log_migrate") if defined?(Rails)

        # Standalone service directory
        candidates << File.expand_path("../../../../../solid_log-service/db/log_migrate", __FILE__)

        # Core gem directory (fallback)
        candidates << File.expand_path("../../../../db/log_migrate", __FILE__)

        # Use first existing directory, or first candidate if none exist
        candidates.find { |path| Dir.exist?(path) } || candidates.first
      end

      # Generate the Ruby migration code
      def generate_migration_content(field, class_name)
        <<~RUBY
          # frozen_string_literal: true

          # Migration auto-generated by SolidLog field promotion
          # Promotes field '#{field.name}' from JSON to dedicated column
          class #{class_name} < ActiveRecord::Migration[8.0]
            def up
              # Add column for promoted field
              add_column :solid_log_entries, :#{field.name}, :#{sql_type(field.field_type)}

              # Add index for efficient querying
              add_index :solid_log_entries, :#{field.name}, name: "idx_entries_#{field.name}"

              # Backfill existing data from extra_fields JSON
              # Process in batches to avoid memory issues
              say_with_time "Backfilling #{field.name} from extra_fields JSON" do
                batch_size = 1000
                offset = 0

                loop do
                  entries = SolidLog::Entry
                    .where.not(extra_fields: nil)
                    .limit(batch_size)
                    .offset(offset)

                  break if entries.empty?

                  entries.each do |entry|
                    begin
                      extra = JSON.parse(entry.extra_fields)
                      value = extra['#{field.name}']

                      if value.present?
                        # Type coercion
                        typed_value = coerce_value(value, '#{field.field_type}')
                        entry.update_column(:#{field.name}, typed_value)
                      end
                    rescue JSON::ParserError, TypeError => e
                      # Skip entries with invalid JSON or type conversion errors
                      next
                    end
                  end

                  offset += batch_size
                end
              end
            end

            def down
              remove_index :solid_log_entries, name: "idx_entries_#{field.name}"
              remove_column :solid_log_entries, :#{field.name}
            end

            private

            def coerce_value(value, field_type)
              case field_type
              when 'number'
                value.is_a?(Numeric) ? value : value.to_f
              when 'boolean'
                [true, 'true', '1', 1].include?(value)
              when 'datetime'
                value.is_a?(Time) ? value : Time.parse(value.to_s)
              when 'string'
                value.to_s
              else
                value
              end
            rescue => e
              nil # Return nil for unconvertible values
            end
          end
        RUBY
      end

      # Map field types to SQL column types
      def sql_type(field_type)
        case field_type
        when "number"
          :float
        when "boolean"
          :boolean
        when "datetime"
          :datetime
        when "string"
          :string
        when "array"
          :text  # Store as JSON text
        when "object"
          :text  # Store as JSON text
        else
          :string  # Default to string
        end
      end
    end
  end
  end
end
